config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"
  resources :recipes do
    resources :ingredients
    collection do
       get 'search_recipe'
       get 'listing_result'
     end
  end
  get "search", to: "search#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :name, presence: true
  validates :name, length: { minimum: 0}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients
	searchkick
	validates :name, presence: true
	validates :name, length: { maximum: 100 }
	validates :instructions, presence: true
	validates :instructions, length: {maximum: 1000}
	validates :cooking_time, presence: true
	validates :cooking_time, length: { minimum: 0}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def create
	  @recipe = Recipe.find(params[:recipe_id])
	  @ingredient = @recipe.ingredients.create(ingredients_params)
	  redirect_to recipes_path
	end
	
	private
	  def ingredients_params
	    params.require(:ingredient).permit(:name)
	  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
	    @recipes = Recipe.all
	  end
	 
	  def show
	    @recipe = Recipe.find(params[:id])
	  end
	 
	  def new
	    @recipe = Recipe.new
	  end
	 
	  def edit
	    @recipe = Recipe.find(params[:id])
	  end
	 
	  def create
	    @recipe = Recipe.new(recipe_params)
	    if @recipe.save
	      redirect_to @recipe
	    else
	      render 'new'
	    end
	  end
	 
	  def search_recipe 
	      @recipe = Recipe.where("name LIKE ?","#{params[:name]}%")
		  @ingredient = Ingredient.where("name LIKE ?","#{params[:ingredient]}%")
		   if params[:name].eql?("") && params[:ingredient].eql?("")
		   	render 'no_data'

		   elsif params[:name].present?
		  	@recipe.each do |recipe|
		  		redirect_to listing_result_recipes_path(recipe)
		  	end	
		  elsif params[:ingredient].present?
		  	@ingredient.each do |ingredient|
		  		redirect_to listing_result_recipes_path(ingredient)
		  	end
		end
		end


	  def listing_result
	  	@recipe = Recipe.find(params["format"].to_i)
	  	@ingredient = Ingredient.find(params["format"].to_i)
	      render 'listing_result'

	  end
	 
	  private
	    def recipe_params
	      params.require(:recipe).permit(:name, :instructions, :cooking_time)
	    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
	  @results = Recipe.search(params[:search])
	  render turbo_stream:
	    turbo_stream.update('recipe', partial: 'recipe/recipe', locals: {recipe: @results})
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/ingredients/_form.html.erb
<%= form_for([@recipe, @recipe.ingredients.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
 
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </p>
 <p>
   <%= f.label :cooking_time %><br>
   <%= f.number_field :cooking_time %>
 </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/recipes/index.html.erb
<h1>Listing Recipes</h1>
<%= form_with url: "/recipes/search_recipe", method: :get do |form| %>
  <%= form.text_field :name, placeholder: "Cuisine" %>
  <%= form.text_field :ingredient, placeholder: "Ingredient" %>
  <%= form.submit "Search" %>
<% end %>
<%= link_to 'New Recipe', new_recipe_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Instructions</th>
    <th>Ingredients</th>
    <th colspan="3"></th>
  </tr>
 
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= recipe.instructions %></td>
      <td><%= recipe.ingredients.first&.name  %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>

    </tr>
  <% end %>
</table>

app/views/recipes/listing_result.html.erb
<h1>Results</h1>
    <tr>
      <td><%= @recipe.name %></td>
      <td><%= @recipe.instructions %></td>
      <td><%= @recipe.ingredients.first&.name  %></td>
    </tr>

  <tr>
    <td><%= @ingredient.name %></td>
  </tr>  

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', recipes_path %>

app/views/recipes/no_data.html.erb
<h1>No data found</h1>

app/views/recipes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @recipe.name %>
</p>
 
<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>
 
 <p>
   <strong>Cooking time:</strong>
   <%= @recipe.cooking_time %>
 </p>
 
<h2>Add a Ingredients:</h2>
<%= render 'ingredients/form' %>
 